spring.application.name=qwack-boot

# Configuration JPA
spring.datasource.url = jdbc:mysql://localhost:3306/quack_shelter
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true